### ISSUE TITLE
the left column of dataiscut out

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#100]
due to several data for the location of this SN the left column of data in the SN page is cut out and type is not visible.

**Comment by guillochon** [comment]
Hey @fedhere, which object page in particular has this issue?

**Comment by fedhere** [comment]
Sorry, it got deleted from the title and I cannot reproduce it. It may have had to do with my browser settings More than anything. I'll reopen if it happens again

**Comment by guillochon** [comment]
No worries!
