### ISSUE TITLE
[SN1996Z] Duplicate data

### ISSUE THREAD

**Issue by MikeFoly** [astrocatalogs/supernovae#102]
There are two sets of light-curve data for this object that appear to be identical except one has errors and the other does not.  The entries without errors should be deleted.

**Comment by guillochon** [comment]
Thanks, data without error bars removed in https://github.com/astrocatalogs/supernovae/commit/929d4723c33c34f38cecbd8b29786c6cf201622f. Data will update on the page in 24 hours.

**Comment by guillochon** [comment]
Closing as this is addressed in https://github.com/astrocatalogs/supernovae/issues/103.
