### ISSUE TITLE
[SN2003bg] wrong classification for reference 1 Galbany+16

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#105]
[Galbany 16](http://iopscience.iop.org/article/10.3847/0004-6256/151/2/33/meta;jsessionid=FE687DA34723BCF08FC397C751DF164C.c3.iopscience.cld.iop.org) actually classifies this as a IIb, not II P as in reported in OSC 
"3. ANALYSIS
Based on their spectral features and/or light curve morphologies, a handful of SNe in our sample have been classified as SNe IIb or SNe II peculiar. This includes: SN 2000cb which shows similar photometric behavior to SN 1987A; SN 2003bg has been classified as SN IIb and studied by Hamuy et al. (2009); SN 2003cv is similar to 2003bg and has also been classified as SN IIb; "

**Comment by guillochon** [comment]
Looks like a typo in Galbany's donation, I've fixed it here: https://github.com/astrocatalogs/sne-external/pull/3

**Comment by guillochon** [comment]
Fixed on the live page, closing.
