### ISSUE TITLE
[SN2003cv] wrong classification for reference 1 Galbany+16

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#106]
Galbany 16 actually classifies this as a IIb, not II Pec as in reported in OSC
"3. ANALYSIS
Based on their spectral features and/or light curve morphologies, a handful of SNe in our sample have been classified as SNe IIb or SNe II peculiar. This includes: SN 2000cb which shows similar photometric behavior to SN 1987A; SN 2003bg has been classified as SN IIb and studied by Hamuy et al. (2009); SN 2003cv is similar to 2003bg and has also been classified as SN IIb; "

**Comment by guillochon** [comment]
See https://github.com/astrocatalogs/supernovae/issues/105

**Comment by guillochon** [comment]
Fixed on the live page, closing.
