### ISSUE TITLE
[SN2005ks] should be type Ic-bl

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#107]
should be Ic-BL: reference 9 the IAUC circular reports "SNe 2005kr and 2005ks are type-
Ib/c supernovae with broad lines similar to that seen in 1998w" and 05s was studies as aIc-BL in [Modjaz+07 ](citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.316.7720&rep=rep1...
) [Modjaz+16](https://arxiv.org/pdf/1509.07124.pdf)

**Comment by guillochon** [comment]
Does that typing happen to appear in a recent reference anywhere? I'm marking all the Ib/c typings as erroneous since clearly the previous lit misread the IAUC.

**Comment by guillochon** [comment]
The IAUC-related typings have been fixed to be Ic-BL, but the first typing listed is still simply "Ic" just because it hasn't appeared in the published literature as being Ic-BL.
