### ISSUE TITLE
[SN2016ezh=PS16dtm] <Should include TDE classification>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#109]
TDE classification from Peter's paper is missing. Bibcode is 2017arXiv170307816B

**Comment by guillochon** [comment]
This should appear in the TDE catalog in addition to the supernova catalog, I'll flag it so it appears in both. Are the HST spectra public for this one yet?

**Comment by mnicholl** [comment]
I think they should be… it was a DDT so probably didn’t have a proprietary period.

**Comment by guillochon** [comment]
OK good. I'm going to port the MAST task to the TDE catalog so all the HST spectra appear there as well.

**Comment by guillochon** [comment]
Done in https://github.com/astrocatalogs/sne-internal/commit/28946f822c01ee7806ce2a78d79ce99ec814a672, live tomorrow. Also PS16dtm is now on the TDE catalog as well: https://tde.space/tde/PS16dtm
