### ISSUE TITLE
[PS17amw] Additional data

### ISSUE THREAD

**Issue by astrofoley** [astrocatalogs/supernovae#110]
This is the same as iPTF17dz:
https://gcn.gsfc.nasa.gov/gcn3/20485.gcn3
https://gcn.gsfc.nasa.gov/gcn3/20398.gcn3
https://gcn.gsfc.nasa.gov/gcn3/20408.gcn3

There are a number of other SNe associated with past GW events.  You might want to look at the LIGO GCN archive to grab the data.

**Comment by guillochon** [comment]
Thanks @astrofoley! Scraping the GCNs is a good idea. In the meantime I've added PS17amw as an alias to iPTF17dz here: https://github.com/astrocatalogs/sne-internal/commit/3482c264a6eed474395867c42a263d1201c3f498, change will be live tomorrow.
