### ISSUE TITLE
[SN2010hc] Incorrect host redshift

### ISSUE THREAD

**Issue by astrofoley** [astrocatalogs/supernovae#112]
NED says this is higher redshift: http://ned.ipac.caltech.edu/cgi-bin/datasearch?search_type=z_id&objid=47736&objname=ESO%20339-%20G%20006&img_stamp=YES&hconst=73.0&omegam=0.27&omegav=0.73&corr_z=1&of=table

Same with the classification circular.

**Comment by guillochon** [comment]
Thanks @astrofoley, fixed in https://github.com/astrocatalogs/sne-internal/commit/0c11898d463bb8f4d826a70233a00f553aae9483, will be live tomorrow night.
