### ISSUE TITLE
[PS15dpq-as-offset] <Descriptive issue title>

### ISSUE THREAD

**Issue by MelissaGraham** [astrocatalogs/supernovae#121]
This Hubble pointing shows up in the OSC as a separate target.

**Comment by guillochon** [comment]
Thanks @MelissaGraham, looks like this pointing conveys no additional useful information so I've gone ahead and marked it for removal: https://github.com/astrocatalogs/sne-internal/commit/e2d784e7483b401a1a1ba0c71187c4578c9a6495
