### ISSUE TITLE
[AT2017ahk] Does not exist?

### ISSUE THREAD

**Issue by astrofoley** [astrocatalogs/supernovae#125]
This is not listed at TNS.  I could not find a SN at these coordinates anywhere else either.

**Comment by guillochon** [comment]
This one is coming from @dbishopx's page, any thoughts David?

A cone search suggests there's nothing nearby, so I'm not sure if it's real either: https://api.sne.space/catalog?ra=01:37:37.000&dec=+15:52:00.00&radius=200

**Comment by guillochon** [comment]
Marking this one as an "erroneous entry," unless @dbishopx says otherwise, https://github.com/astrocatalogs/sne-internal/commit/fa9a7779cfcd843a48581952ae9c23c8bf761995. This should move the object to the graveyard in the next update.
