### ISSUE TITLE
[PTF10duy] Misattributed source?

### ISSUE THREAD

**Issue by astrofoley** [astrocatalogs/supernovae#126]
It looks like this new sample of objects may have been incorrectly attributed to http://adsabs.harvard.edu/abs/2017MNRAS.472.3437G "Nebular-phase spectra of nearby Type Ia Supernovae" instead of correctly attributed to http://adsabs.harvard.edu/abs/2014MNRAS.444.3258M "Exploring the spectral diversity of low-redshift Type Ia supernovae using the Palomar Transient Factory"

(1) Cross-checking several objects in the Maguire et al. sample, they all appear to have "Graham et al." data on OSC.

(2) All of the objects appear to be PTF objects and have R-band light curves (and no other band).  As PTF generally observed in R band, while LCOGT usually observes in many bands (and I'm not even sure if they have an R band), I would bet the light curves came from PTF, which is the source of the Maguire light curves.

(3) The abstract of the Maguire paper talks about "optical spectra of 264 low-redshift (z < 0.2) Type Ia supernovae (SNe Ia) discovered by the Palomar Transient Factory" similar to the 258 Type Ia of the update.  Meanwhile, the Graham paper only has 8 objects.

Perhaps there was some confusion between a couple of different papers and/or sources?

**Comment by guillochon** [comment]
Thanks @astrofoley, you are correct, this is the result of two e-mail threads being crossed. I've replaced the references and the corrected references will go live tomorrow.

**Comment by guillochon** [comment]
Fixed in https://github.com/astrocatalogs/sne-internal/pull/111.
