### ISSUE TITLE
Add columns to main table for earliest/latest spec/phot epochs

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#132]
It would be really really useful if the main table could display columns showing 'earliest spec epoch', 'latest spec epoch', and same for photometry, given relative to date of maximum light. With the typical search logic on these columns it would allow to see which transients really have 'early-' or 'late-'time data according to whatever criterion one wants to define, e.g. show only SNe with spectra later than 100 days

**Comment by guillochon** [comment]
Not quite what you requested, but should accomplish the same thing: there's now an entry field below the pre-/post- checkboxes that allows one to specify a number of days relative to max:
![image](https://user-images.githubusercontent.com/4998058/40628011-3b4eadf0-6277-11e8-8331-280521660aa1.png)
Now it's trivial to find the events with early- or late-time photometry/spectroscopy!
