### ISSUE TITLE
[PTF11bij] Photometry entry has bad e_magnitude

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/supernovae#133]
[PTF11bij](https://sne.space/sne/PTF11bij/) has a large negative value of the `e_magnitude` field:
```json
			{
				"time":"55643.325",
				"band":"g",
				"e_magnitude":"-99.",
				"magnitude":"21.38",
				"telescope":"Palomar 60-in",
				"u_time":"MJD",
				"source":"2"
			},
```

**Comment by guillochon** [comment]
It appears like this error is in the original paper: 
![image](https://user-images.githubusercontent.com/4998058/40079112-c74e4946-5854-11e8-9ef3-016199758037.png)

I've removed the `e_magnitude` attribute from this measurement, the update will be live on the OSC by tomorrow night.

**Comment by guillochon** [comment]
Live on the OSC now, closing.
