### ISSUE TITLE
[SN2013dy] Not Able to Download Data (Server Error?)

### ISSUE THREAD

**Issue by rrgupta** [astrocatalogs/supernovae#136]
The page for this SN (https://sne.space/sne/SN2013dy/) displays the available data, but the button to Report An Issue does not work and is occluded by the Spectra plot (I had to hack the Report An Issue URL from another SN to get here). Also the download data buttons as well as the API fail for this SN (they give "Page Not Found" or "Internal Server Error"): 
https://sne.space/astrocats/astrocats/supernovae/output/json/SN2013dy.json
https://api.sne.space/SN2013dy/spectra/time+data+instrument+telescope+source

Thanks.

**Comment by rrgupta** [comment]
Sorry, I just noticed this is a duplicate of #129 !
I guess you're already aware of this

**Comment by guillochon** [comment]
Thanks for pointing this out again, I'll make it high priority to fix this.
