### ISSUE TITLE
[SN2007in] and [SN2007io] Erroneous coordinates

### ISSUE THREAD

**Issue by rrgupta** [astrocatalogs/supernovae#139]
Due to what I *believe* is a transcription error on the part of the [Bright Supernova Page](http://www.rochesterastronomy.org/snimages/snredshiftall.html) the RAs for SN2007in and SN2007io were copied wrong from the original [CBAT](http://www.cbat.eps.harvard.edu/iau/cbet/001000/CBET001063.txt). 

Specifically, the RA for 2007in in the CBAT reads "1:08:13.68" but this was mistyped as "1:08:03.68" into the BSP. Similarly, the RA for 2007io in the CBAT is "1:04:47.69" but appears as "1:04:07.69" in the BSP.

**Comment by guillochon** [comment]
Thanks @rrgupta, fixed in https://github.com/astrocatalogs/sne-internal/pull/134, should be live by tomorrow.
