### ISSUE TITLE
[PTF10nlg] and [PTF10ndc] Coordinates from ATel Swapped

### ISSUE THREAD

**Issue by rrgupta** [astrocatalogs/supernovae#141]
Hi James,
I believe that due to a misreading of this [ATel](http://www.astronomerstelegram.org/?read=2735), the coordinates sourced from this ATel for [PTF10ndc](https://sne.space/sne/PTF10ndc) and [PTF10nlg](https://sne.space/sne/PTF10nlg) have been accidentally swapped. 
I.e., 10ndc should have coordinates RA=17:19:50.18, DEC=+28:41:57.5 while 10nlg should have RA=16:50:34.48, DEC=+60:16:35.0.

Thanks,
Ravi

**Comment by guillochon** [comment]
Fixed in https://github.com/astrocatalogs/sne-internal/pull/135, should be live tomorrow evening.
