### ISSUE TITLE
[SN2004bv] Incorrect R.A. copied over from IAUC

### ISSUE THREAD

**Issue by rrgupta** [astrocatalogs/supernovae#142]
Looks like the R.A. from the [IAUC](http://www.cbat.eps.harvard.edu/iauc/08300/08344.html) (20:25:06.34) was mistakenly entered into the database as 19:25:06.34

**Comment by guillochon** [comment]
Fixed in https://github.com/astrocatalogs/sne-internal/pull/135, should be live tomorrow evening.
