### ISSUE TITLE
[SNhunt346/SN2018pi] Error page

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/supernovae#144]
The main table has item `SNhunt346/SN2018pi` that links to https://sne.space/sne/SNhunt346_SN2018pi/. This page contains no data but message `Error: Invalid event name "SNhunt346_SN2018pi"! [SNhunt346_SN2018pi]`

**Comment by guillochon** [comment]
This should be addressed in https://github.com/astrocatalogs/supernovae/commit/e179588071d9ab4a6e132d45400eb8f70caa30c0. Will close issue when fix is live.
