### ISSUE TITLE
Catalog entries link to wrong data pages

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/supernovae#146]
Some items links to the page with the data for another object and following message:
"Warning: Exact event name "`PART OF THE ORIGIN NAME`" not found, returning closest match."

The items with such behaviour I've found:
```
PS1-13dat
PS15dat
PS16dat
PS17dat
PTF13dat
iPTF13dat
SN candidate in PGC066672
SN candidate in SDSSJ124138.20+474742.9
```

"dat" is a part of all these names

**Comment by guillochon** [comment]
Sorry I missed this until now! This was a silly redirect issue where I was using `.dat` to match files ending in that extension, but the `.` was being interpreted as a wildcard. This has now been fixed and all the above events should now be accessible.
