### ISSUE TITLE
Possible duplicate records: "CSS100217" and "CSS100217:102913+404220"

### ISSUE THREAD

**Issue by shiaki** [astrocatalogs/supernovae#147]
In the open TDE catalog, "CSS100217" is an alias of "CSS100217:102913+404220". However, they are two separate records in OSC. I guess this is a duplicate.

Best,
YJ

**Comment by guillochon** [comment]
Thanks for pointing this out, the two events are now merged via https://github.com/astrocatalogs/sne-internal/commit/100a2a1471d8d7d4d08735d847ef6c67a996ff67 and the web page will be updated by tomorrow night.

**Comment by shiaki** [comment]
Great! Thank you for maintaining this very useful data source.
