### ISSUE TITLE
[SN2011kf] host field is missed in schema

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/supernovae#150]
Some of photometry items have `host` filed, that is not specified in [the corresponding schema](https://github.com/astrocatalogs/supernovae/blob/5d080fc/SCHEMA.md). Should this field have name `includehost`?

**Comment by guillochon** [comment]
Thanks for bringing this up @hombit, the schema has actually moved to here now: https://github.com/astrocatalogs/schema (I've [redirected the old schema link](https://github.com/astrocatalogs/supernovae/commit/d3ef5fca305304d1663823b0975fbe2a63dbfc95) to that new location, to avoid future confusion).

That being said, the current schema was *also* missing the `host` attribute for `photometry`, a description has now been added in https://github.com/astrocatalogs/schema/commit/b828549ce8c34fc54453672b323723fade806e58.
