### ISSUE TITLE
[OGLE-2012-SN-006] JSON bandset field is missed in Schema

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/supernovae#153]
It seams that `bandset` JSON field is missed in [Schema](https://github.com/astrocatalogs/schema). Please, can you describe it?

**Comment by guillochon** [comment]
Thanks for pointing out this omission, I have added a description to the Schema (https://github.com/astrocatalogs/schema/blob/master/README.md). It is currently not a very widely used attribute in the catalogs.
