### ISSUE TITLE
[OGLE-2014-SN-131] Incorrect redshift (Should be 0.085)

### ISSUE THREAD

**Issue by emirkmo** [astrocatalogs/supernovae#154]
The redshift of OGLE-2014-SN-131 should be changed from 0.31 to 0.085. The initial estimate of 0.31 is wrong (see Karamehmtoglu et al. 2017, one of the sources of the data for this object). The initial redshift estimate reported in the ATEL was incorrect. The correct redshift is in the paper.

**Comment by guillochon** [comment]
Apologies for the belated response to this, this is address in https://github.com/astrocatalogs/sne-internal/pull/145, and the correction will be live on the catalog by tomorrow night.
