### ISSUE TITLE
A few objects with Gaia photometry are returning {"message": "Internal Server Error"} when attempting to download light curve

### ISSUE THREAD

**Issue by gmzsebastian** [astrocatalogs/supernovae#157]
A few objects (e.g. AT2018gfo, AT2018gfn, AT2018gfm, AT2018gfl, AT2018gfb, AT2018gew, AT2018ger) return an {"message": "Internal Server Error"}  when I click on "json" or "csv" to try to download the photometry. The same error happens when querying the API.

The only similarity I can see among these objects is that they all have several Gaia data points. Then objects like Gaia18ctb, which exclusively has Gaia photometry, returns an empty array instead of the 56 detections.

Might this be a problem on Gaia's end, or the OSC?

Thanks!

**Comment by guillochon** [comment]
This appears to be an issue with events that were added via the TNS alerts; if the primary name is not ATXXXX then it looks for the wrong file when attempting to retrieve the photometry. I've restarted the API which temporarily fixes the issue for all the events you listed above, but it will likely recur for newer events. Looking into fixing the issue.

**Comment by guillochon** [comment]
I believe that this is fixed in https://github.com/astrocatalogs/OACAPI/commit/163807bfb841e1f9d82234412d7a983aac05118a. Let me know if you encounter this issue again though.

**Comment by gmzsebastian** [comment]
That appears to have solved the problem! Thanks.
