### ISSUE TITLE
Cannot find 2015bn

### ISSUE THREAD

**Issue by bkornpob** [astrocatalogs/supernovae#162]
I was trying to find some SNe just right now, and I could not find it. Then, I realized that 2015bn was not in the data table. Then, I put 2015bn in the search bar and result was no match. I attached a picture as having 2015bn on the search bar.

I used it on the new year eve, and I did not notice any problem. So, I don't know if it is something wrong with my computer or else.

![osc](https://user-images.githubusercontent.com/13034318/50613753-a8c29900-0eac-11e9-9b2c-42769bd7da8e.png)

**Comment by guillochon** [comment]
Closing, will track in https://github.com/astrocatalogs/astrocats/issues/93
