### ISSUE TITLE
[SN2002gd] <JD is not mentioned in spectra>

### ISSUE THREAD

**Issue by rayadastidar** [astrocatalogs/supernovae#164]
The spectroscopic data of SN 2002gd has 29 spectra. However, for the first 12 spectra, no JD is mentioned. Please update the JD of these.

**Comment by guillochon** [comment]
Hi @rayadastidar, if we don't have them they likely weren't reported in the original source. If you happen to find the JDs in the listed sources, please let us know and we'll add them!

**Comment by rayadastidar** [comment]
I got the log of the observations here [http://www.das.uchile.cl/~mhamuy/CATS/sn2002gd.log.html], but still not sure of the order in which the spectra are numbered in OSC.

**Comment by rayadastidar** [comment]
Hi, the data can be updated from [https://csp.obs.carnegiescience.edu/data](url).
