### ISSUE TITLE
[SN2012ap] missing R and I photometry

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#25]
The data available is UBV but also RI, all in http://iopscience.iop.org/article/10.1088/0004-637X/799/1/51/pdf (i can dowload and upload the data myself later today)

**Comment by guillochon** [comment]
So @danmil-gh and I were just talking about how this one was missing. Link me to the ASCII and I'll add it.

**Comment by fedhere** [comment]
http://iopscience.iop.org/0004-637X/799/1/51/suppdata/apj505272t1_ascii.txt
and also swift u b v http://iopscience.iop.org/0004-637X/799/1/51/suppdata/apj505272t2_ascii.txt

**Comment by danmil-gh** [comment]
Thanks Federica!

Note that it was brought to my attention (after publication) by Natasha
Karpenka that a measurement plotted in a figure in the paper was not
included in the Table:

MJD               B             B(err)
55967.246   18.407     0.156

**Comment by guillochon** [comment]
@danmil-gh Is that observation for KAIT or UVOT?

**Comment by guillochon** [comment]
OK I figured out that the observation was from KAIT, and this commit adds the data to the catalog, should appear in the next update and will close when it does: https://github.com/astrocatalogs/supernovae/commit/cda645ff584e494c3127b348223da372c0df99fd

**Comment by guillochon** [comment]
KAIT observations now live, closing.
