### ISSUE TITLE
[SN2006jd] classification

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#27]
The early IIb classification by Modjaz is withdrawn. Maryam (sitting here) confirms the later evolution supports the typing as IIn, not IIb

**Comment by guillochon** [comment]
Cool! Is the new classification published anywhere? Alternatively we can cite the code used to make the classification.

Ideally all types should have attached citations, otherwise I think I'd just tag the source as "Modjaz, priv. comm.".

**Comment by fedhere** [comment]
the IIn classification is already in the list of claimed types for this object (w citations to Barbon 08 and others)

**Comment by guillochon** [comment]
OK, so the IIn typing for this object is the "preferred" typing, it is listed first and appears in the main catalog table as the default value for it. There are three sources that list it as IIb, including TNS and the Latest Supernova page, and this IAUC: http://adsabs.harvard.edu/abs/2006IAUC.8762....2Y, but I actually don't see Mariam being cited for a IIb classification. So I'm not sure if there's much else to be done for this one, the correct typing is currently displayed by default.

**Comment by fedhere** [comment]
I dont see the type in the disovery IAUC which you linked, just the discovery. The typing from circulars (which is what Maryam was referering to ) is in this later CBET
http://www.cbat.eps.harvard.edu/iau/cbet/000600/CBET000679.txt

**Comment by guillochon** [comment]
OK I have marked the IIb typing as erroneous (https://github.com/astrocatalogs/sne-internal/commit/76489338e8d9ffa4973c794d9f276106c7611fb4). It will be removed in the next update.
