### ISSUE TITLE
[Additional Spectra] R. Foley repo

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#3]
_From @jparrent on May 18, 2016 5:4_

https://github.com/astrofoley/astr596/tree/master/data/spectra

This is a pile of spectra that needs to be sifted through. I will do this and will supply what the catalog does not already have. 

_Copied from original issue: astrocatalogs/astrocats#38_

**Comment by jparrent** [comment]
I cannot say with 100% certainty that we have all the data in that repo, but it appears so. The data come from repos we've scraped. Closing.
