### ISSUE TITLE
[PTF11iqb] secondary type IIb not motivated

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#30]
This is a IIn, but you also report IIb, with reference to the general wise rep paper, but everywhere in the literature this appears as a IIn

**Comment by guillochon** [comment]
@jparrent I noticed that you are listed as the reducer of this particular spectrum. What are your thoughts on the IIb vs. IIn typing?

**Comment by guillochon** [comment]
@jparrent Pinging you again on this one, thoughts on the typing?

**Comment by jparrent** [comment]
@guillochon Pardon the delay. I agree with Fed, this is a IIn. Not sure how IIb got in there.

**Comment by guillochon** [comment]
@jparrent OK got it, marked as erroneous in https://github.com/astrocatalogs/sne-internal/commit/1f0bf7192a4029959b584d395acd71ee5c75d11a.

**Comment by guillochon** [comment]
The type IIb typing is removed in the catalog, closing.
