### ISSUE TITLE
[SN2005em] wrong CBET citation  for type

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/supernovae#32]
Hi,
the CBET that should be cited to support the IIb typing is 08611, not 8604. http://www.cbat.eps.harvard.edu/iauc/08600/08611.html#Item2 
I found this to be the case for a couple objects: I think the issue is that the discovery telegrams, which you cite for the discovery, generally do not have typing because they are based on photometry, and typing requires spectra. So typing traditionally occurs in a following telegram (and then often in many revisions afterwards...).

**Comment by guillochon** [comment]
So most of the incorrect CBET/ATel/IAUC associations come from David Bishop's page, unfortunately he's the only one who is manually transcribing these, and he sometimes makes mistakes. Best we can do is correct the issues when we find them and perhaps ask David to be a bit more wary in the future.

**Comment by guillochon** [comment]
This one has been addressed here: https://github.com/astrocatalogs/sne-internal/commit/edd65dee43cb420b25e4efa5c21343c197d3f1d6
