### ISSUE TITLE
[LSQ12dlf] missing U-band data

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#38]
Should check PESSTO task for bugs

**Comment by guillochon** [comment]
@mnicholl I've checked the event again and it appears all the U-band data in the file is in the plot, it's just that the U-band is behind the other colors in the plot (zoom in and you can see the same 5 points as in the file). Can you double-check that all the U-band data is there at your earliest convenience?

**Comment by mnicholl** [comment]
Right it does look like its in there! My bad!

**Comment by guillochon** [comment]
Great, closing!
