### ISSUE TITLE
[SN1983G] Wrong reference

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#4]
_From @jparrent on May 12, 2016 5:3_

The spectra of 83G from SuSpect do not have the correct reference because SuSpect does not have the correct reference. Instead the pointer is to Cristiani et al. (1992), which is on SN 198**6**G, not 83G. Searching for the original work brings up nothing, and the last hint from SuSpect is that the data were donated by the Asiago SN Group. http://graspa.oapd.inaf.it/

Fortunately I was able to use SNID to determine that the wavelength solution is fine and in the observer frame for the files. 

BTW there really is a SN 1983G, but the spectra can only be found through GELATO (another SNID-like tool): https://gelato.tng.iac.es/. Which means the spectra can only be seen after submitting a spectrum for comparison. 

https://gelato.tng.iac.es/templates/
"The templates database is continuously growing with new additions, which are immediately available to all GELATO users. GELATO currently uses 2926 template spectra to classify your SNe." 

"Available" in GELATO, not available for download. 

_Copied from original issue: astrocatalogs/astrocats#35_

**Comment by guillochon** [comment]
Fixed in source, will close after verifying.

**Comment by guillochon** [comment]
_From @jparrent on May 23, 2016 2:2_

The reference is in the bib list now, but the spectra are not being referenced to it (#15).

**Comment by guillochon** [comment]
@jparrent Is this one resolved now?

**Comment by jparrent** [comment]
This is done now, closing.
