### ISSUE TITLE
[SN2016ard] <wrong redshift>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#45]
z=0.20 rather than 0.02

**Comment by guillochon** [comment]
Have a source for the correct redshift? Not currently listed on TNS.

**Comment by guillochon** [comment]
Corrected in https://github.com/astrocatalogs/sne-internal/commit/0709812af70bd2b7664cb98eb73a3f9fd307585e, correction should appear by tomorrow afternoon.

**Comment by guillochon** [comment]
Fix is live, closing.
