### ISSUE TITLE
[SN2003dh] spectra epoch dates incorrect

### ISSUE THREAD

**Issue by villrv** [astrocatalogs/supernovae#46]
All of the spectra say they are from 2000+ days after peak, but the ones from [16] are taken within 2 months of peak and those from [13] are taken within a year of peak

**Comment by guillochon** [comment]
The photometry here is clearly off, peaking in 1995, suggesting a bad date conversion. I'll check it out.

**Comment by guillochon** [comment]
Was accidentally using "time since burst" as the time column, fixed in https://github.com/astrocatalogs/supernovae/commit/315355845b9dc57c21ecc8b657bc200eac71f56c. Will close once page updates tomorrow night.

**Comment by guillochon** [comment]
This is now fixed on the live page, closing.
