### ISSUE TITLE
[SN2005kf] Need redshift

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#48]
SN2005kf has spectra available, but no measured redshift. This should be derivable from the available spectra. @jparrent if you have time.

**Comment by jparrent** [comment]
@guillochon fortunately Modjaz et al. went ahead and derived this from H II emission lines present in the spectra. 
Specifically, c * z_helio = 4522 km/s; z = **0.0151**.

**Comment by guillochon** [comment]
Splendid! Added in https://github.com/astrocatalogs/sne-internal/commit/b827cd70d99549345bcbd4d1ed3e2ec559fb806b. Closing.
