### ISSUE TITLE
[SN2006nx] SN2006nx is also a Ic-BL

### ISSUE THREAD

**Issue by villrv** [astrocatalogs/supernovae#51]
Several sources, (eg Nicholl 16; 1503.03310 and Modjaz 07; 0701246), have re-classified 06nx as a Ic-BL.

**Comment by guillochon** [comment]
Thanks @villrv, [here's a link](https://github.com/astrocatalogs/sne-internal/new/master/?filename=SN2006nx.json&value=%23%23%23%20DELETE%20THIS%20LINE%20TO%20ENABLE%20COMMIT%20BUTTON%0A%7B%0A%09%22SN2006nx%22%3A%7B%0A%09%09%22name%22%3A%22SN2006nx%22%2C%0A%09%09%22sources%22%3A%5B%0A%09%09%09%7B%0A%09%09%09%09%22bibcode%22%3A%22%23%23%23%20BIBCODE%20FOR%20NEW%20VALUE%20%23%23%23%22%0A%09%09%09%7D%0A%09%09%5D%2C%0A%09%09%22claimedtype%22%3A%5B%0A%09%09%09%7B%0A%09%09%09%09%22value%22%3A%22%23%23%23%20NEW%20VALUE%20%23%23%23%22%2C%0A%09%09%09%09%22e_value%22%3A%22%23%23%23%20ERROR%20IN%20VALUE%20(if%20applicable)%20%23%23%23%22%2C%0A%09%09%09%09%22u_value%22%3A%22%23%23%23%20VALUE%27S%20UNIT%20(if%20applicable)%20%23%23%23%22%0A%09%09%09%7D%0A%09%09%5D%0A%09%7D%0A%7D&message=%22claimedtype%22%20added%20to%20SN2006nx.) that will allow you to add the new typing.

**Comment by guillochon** [comment]
Hey @villrv, when you have a chance it would be great to add this bit of data. Thanks!

**Comment by guillochon** [comment]
Type now appears on the OSC, closing.
