### ISSUE TITLE
[LSQ14bdq] <More precise redshift>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#53]
The redshift for this one should be z=0.345 (Nicholl et al 2015 - source 2).
The quoted value of 0.35 is just the approximate redshift from the initial classification

**Comment by guillochon** [comment]
Addressed here: https://github.com/astrocatalogs/sne-internal/commit/19ea8a59140a877c4e78ad3037688ebd70c800a8
