### ISSUE TITLE
[SN2006oz] <wrong redshift>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#54]
Should be 0.376 from the Leloudas et al 2012 paper (source 4)

**Comment by guillochon** [comment]
Do you have an error bar for that? The Sako ref supercedes this one because it has an error bar reported. Should I mark the Sako ref as being erroneous?

**Comment by guillochon** [comment]
Fixed in https://github.com/astrocatalogs/sne-internal/commit/4cb139f32dfb8dcfd21c112f62d018a5fa68f4b1.
