### ISSUE TITLE
[SN2016els] <Pan-STARRS upper limits not trustworthy!>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#56]
Think we talked about this a while back, but just to make it a formal issue:
A lot of PS1/PSST upper limits are not real (detector gaps etc). This is clearly the case here (and presumably for many other objects) where there are simultaneous detections and limits in the same filter.
Would certainly mess up any attempts to grab and model with mosfit!

**Comment by guillochon** [comment]
Do you know who we could contact to clear this up? It would be great to clear up whatever logic the current 3pi page is employing.

**Comment by mnicholl** [comment]
Sent an email to my friends at QUB, let's see what they say...

**Comment by mnicholl** [comment]
"Hi Matt 
OSC shouldn't import these limits. 

We should fix, it's still on a development list but is not the highest priority. But until it's fixed those numbers shouldn't be imported by any "catalogue". 

They're just a guide and have to be taken as such. I do want them fixed but can't give a timescale for Ken to do it. 
Stephen"

**Comment by guillochon** [comment]
These should be removed in https://github.com/astrocatalogs/supernovae/commit/aca6128c753570679c6f8223bfe127e7834fcf6c, changes live by tomorrow.
