### ISSUE TITLE
[SSS120810:231802-560926] <Incorrect redshift>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#58]
Redshift should be z=0.156 from Nicholl et al 2014 (source 4)

**Comment by mnicholl** [comment]
+/-0.001

**Comment by guillochon** [comment]
Go ahead and add that to sne-internal, the fact that it has an error bar will supercede the WISeREP value.

**Comment by guillochon** [comment]
Looks like this one was never added @mnicholl, could you add the new redshift at your leisure?

**Comment by guillochon** [comment]
Live on the OSC, closing.
