### ISSUE TITLE
[SN2013dg] <Wrong redshift>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#59]
Redshift should be z=0.265 from Nicholl et al 2014 (source 2)

**Comment by mnicholl** [comment]
+/-0.005

**Comment by guillochon** [comment]
Same here, go ahead and add to sne-internal.

**Comment by mnicholl** [comment]
where does sne-internal live?

**Comment by guillochon** [comment]
It's the same repo you were submitting files to earlier today: https://github.com/astrocatalogs/sne-internal

**Comment by mnicholl** [comment]
Oh as in click on the pencil icon!

**Comment by guillochon** [comment]
Right, but you don't have to use the catalog interface to interact with it.

**Comment by mnicholl** [comment]
After you merge the changes how long before they appear on OSC?

**Comment by guillochon** [comment]
After the daily update, which finishes around noon every day. So tomorrow by noon.

**Comment by guillochon** [comment]
Live on the OSC, closing.
