### ISSUE TITLE
[Superfit] Redshift corrections, dupes, and epochs

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#6]
_From @jparrent on May 5, 2016 18:11_

I believe I'm coming to a consensus on the Superfit spectra. It's fine if and when they are shown, but:
--they appear to be rest frame spectra, so they need not be corrected for redshift in the import script. There may be exceptions, but for the most part this is true, and I'm tracking the exceptions.
--the epochs for some spectra appear to be the negative of what they should be, e.g., day -116 for 90aa I'm guessing should go to +116. This seems to be the case for others, and the underlying thing here is that there are a few naming conventions for the superfit files. Anything with a "m05" in the filename refers to day -5 in the usual sense, but for post-max, there are two different conventions, "u" and "p", both apparently meaning +number of days since maximum light.

_Copied from original issue: astrocatalogs/astrocats#28_

**Comment by guillochon** [comment]
@jparrent Status update on this one?

**Comment by jparrent** [comment]
@guillochon So here's what's going on for this issue at the moment (`sne-external-spectra/superfit`):

`II/sn1979C.p72.dat` correctly shows up with 'Rest frame days to max' of +72, but for some reason the following spectra for this object are not showing up:
`sn1979C.p07.dat
sn1979C.p11.dat
sn1979C.p43.dat` 

Same goes for 84E, 80K, and I'm assuming others in `superfit/`; for 80K the +41 spectrum shows up correctly labeled, but skips the first two for that object.

**Comment by guillochon** [comment]
OK I think I finally tracked this one down, filenames weren't being added to Superfit spectra which was causing all spectra aside for the first one added to an event to be considered as "dupes", this commit should fix that: https://github.com/astrocatalogs/supernovae/commit/84bdffb642f2b195d35c24428fd8fed0be9fbe31

Will close with next catalog update if fixed.

**Comment by jparrent** [comment]
Awesome, all spectra are up. Now the original epochs issue:

This appears to be resolved, or mostly. There was an error in the original filename for one object (p83 instead of p22 for SN1986I), and another with an unclear epoch ('u31' for SN1997cy) and a corrupted wavelength offset. I have dealt with these and followed with a PR.

This issue is now closed, and if epochs come up again for the superfit files, it will be related to the epochs in the original filenames.
