### ISSUE TITLE
[SSS120810:231802-560926] <Source 5 does not say Type Ia>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#61]
The typing as a Ia is attributed to an ATel and to the bright SN page. Although the bright SN page does say Type Ia and attributes it to the ATel, the ATel actually says nothing of the sort!

Primary type should be SLSN (it's most definitely not a Ia!) attributed to ref 4 (Nicholl paper)

**Comment by guillochon** [comment]
Go to the [individual event page](https://sne.space/sne/SSS120810:231802-560926/) and then hover over the "Ia" type with your mouse, a "mark as erroneous" button should appear. Click that button and you'll see how to mark a value as erroneous in the JSON.

**Comment by guillochon** [comment]
Should be fixed now by your latest edit, closing.
