### ISSUE TITLE
[SN2006oz] <duplicate data>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#62]
There are 2 data sets here, one from Sako et al and one from Leloudas et al. They are the same except for an offset of about half a day... The Leloudas one includes upper limits but Sako doesn't - is it possible to throw out the less complete data set and just keep the Leloudas one? In its current state it will mess up the fitting process

**Comment by guillochon** [comment]
I'll blacklist Sako on that event. Are there any other events affected?

One nice option for MOSFiT might be an "ignore references" option, then the user provides a list of bibcodes and/or ref names. Thoughts?

**Comment by guillochon** [comment]
Duplicate data removed, closing.
