### ISSUE TITLE
[SN2010md] <Duplicate swift data>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#63]
This dataset includes Swift mags twice, once in AB and once in Vega. 'Brighter' ones are vega and 'fainter' ones are AB. Let's please just have one of these included, with the appropriate system tag!

**Comment by guillochon** [comment]
Am using the Inserra donation (in AB) instead of your older donation of this guy.

**Comment by guillochon** [comment]
Duplicate data now removed, closing.
