### ISSUE TITLE
[Gaia16bao] Not a supernova ?

### ISSUE THREAD

**Issue by JohnAstronomer** [astrocatalogs/supernovae#69]
The light curve for this object does not appear to be a supernova - it has two significant dips rather than a single increase. I think the Gaia auto classification software was probably confused by this object and this classification as a SN has been carried over to this site.

**Comment by guillochon** [comment]
Thanks @JohnAstronomer! I confirm the Gaia page notes this object is a star, I've marked it as such in https://github.com/astrocatalogs/sne-internal/commit/391770cd71e82a18e8251c9bdd485c89c2189573. The change will be reflected on the page in about a day.
