### ISSUE TITLE
[iPTF13ajg] <Host mags!>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#73]
Points after MJD 56600 are observations of the host rather than the transient

**Comment by guillochon** [comment]
This should be addressed by https://github.com/astrocatalogs/supernovae/commit/d381e5fd936c8551d9104855af7a86ac54a43ce7, changes live tomorrow afternoon.

**Comment by guillochon** [comment]
Actually, looking at this a little closer: Any idea why the host magnitude would change in R_s and g? 
![image](https://cloud.githubusercontent.com/assets/4998058/23908879/98008bda-08ab-11e7-99cd-14deb5215e11.png)

**Comment by mnicholl** [comment]
I suspect that the errors on those points are grossly underestimated!

**Comment by guillochon** [comment]
This is live now, closing.
