### ISSUE TITLE
[PS1-10ahf] <z=1.158>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#75]
Redshift reported by McCrum et al (source 2) is 1.158, not simply 1.1

**Comment by guillochon** [comment]
1.1 appears as the redshift in the VizieR table: http://vizier.cfa.harvard.edu/viz-bin/VizieR-3?-source=J/MNRAS/448/1206/table5&-out.max=50&-out.form=HTML%20Table&-oc.form=sexa

Where's the 1.158 from?

**Comment by guillochon** [comment]
The 1.158 was in an early draft, the published number is indeed 1.1.
