### ISSUE TITLE
'data' key does not exist in json for some spectra

### ISSUE THREAD

**Issue by gdhungana** [astrocatalogs/supernovae#77]
Opening the downloaded json with supernovae.scripts.json_to_spec:
```python
In [1]: from supernovae.scripts import json_to_spec
File to read:  SN1999em.json
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-c3900d084b67> in <module>()
----> 1 from supernovae.scripts import json_to_spec

...../osc/supernovae/scripts/json_to_spec.py in <module>()
     17 
     18 for i in range(len(data[sn]['spectra'])):
---> 19     test = np.array(data[sn]['spectra'][i]['data'])
     20     test2 = np.vectorize (float) (test)
     21     plt.plot(test2[:,0],test2[:,1])

KeyError: 'data'
```
Opening the file and looking for keys:
```python
In [2]: import json

In [3]: file='SN1999em.json'

In [4]: sn=file.split('.')[0]

In [5]: f=open(file,'r')

In [6]: data=json.load(f)

In [7]: len(data[sn]['spectra'])
Out[7]: 72

In [8]: data[sn]['spectra'][0].keys()
Out[8]: [u'exclude', u'source', u'filename']

In [9]: data[sn]['spectra'][1].keys()
Out[9]: [u'exclude', u'source', u'filename']

In [10]: data[sn]['spectra'][2].keys()
Out[10]: 
[u'u_wavelengths',
 u'u_errors',
 u'filename',
 u'source',
 u'u_time',
 u'time',
 u'data',
 u'u_fluxes']

In [11]: 
```
As you can see, there is no data key for first two spectra.

**Comment by guillochon** [comment]
Thanks for the report, this appears to be a bug where spectra that have been marked up by users are not being imported properly. I am looking into it.

**Comment by guillochon** [comment]
I believe I have identified and fixed the bug. The spectra will hopefully appear in the datafiles tomorrow after the daily update.

This bug probably affects a few dozen spectra in the catalog.

**Comment by gdhungana** [comment]
Great! Glad that was an easy fix. Presently, I am just looking at few objects that I have already downloaded. Please close this once you have tested your updates. I will use the same module for extraction next time I download other spectra :-) Thanks for this nice work!

**Comment by guillochon** [comment]
I believe this is now fixed, please verify when you have a moment. Thanks very much for bringing this to our attention!
