### ISSUE TITLE
[SN2013dy] NIR data not loaded from Pan et al. 2015

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#78]
1. The Pan et al. 2015 data don't appear to have been included in the SN 2013dy entry.
http://adsabs.harvard.edu/abs/2015MNRAS.452.4307P

**Comment by guillochon** [comment]
Yep we're missing that paper, but I've just added it and it should appear tomorrow.

**Comment by guillochon** [comment]
Sorry for the delay, the daily update was broken for a few days due to some software updates. The NIR data is now up.
