### ISSUE TITLE
[SN2013dy] Zhai et al. data loaded with unrealistically large error bars

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#79]
The error bars are clearly too large (e.g., all ~1 mag) for the UBVRI points from Zhai et al.
http://adsabs.harvard.edu/abs/2016AJ....151..125Z

**Comment by guillochon** [comment]
Thanks for reporting, the data table actually reported the errors in centimag (!) rather than mag. Should be fixed by tomorrow's update.

**Comment by guillochon** [comment]
This has been fixed, closing.
