### ISSUE TITLE
Weyant et al. 2017 SweetSpot improvements for units, telescope, instrument, and time.

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#80]
The photometry points imported from Weyant et al. 2017
https://arxiv.org/abs/1703.02402
could be improved to clarify units, telescope, and time.

```
   {'band': 'H',
    'countrate': '643.7012',
    'e_lower_countrate': '12.7196',
    'e_lower_magnitude': '0.0216675',
    'e_upper_countrate': '12.7196',
    'e_upper_magnitude': '0.0212450',
    'magnitude': '17.97829',
    'source': '3',
    'telescope': 'WHIR',
    'time': '56608.152234',
    'u_time': 's^-1',
    'zeropoint': '25'},
```

`telescope` should be `'WIYN'`
`instrument` should be `'WHIRC`'
`u_time` should be `MJD`

While `countrate` is not actually a counts/second -- it's just flux normalized to a zeropoint=25 -- absent a better clarifying unit, perhaps that's fine.  I didn't see anything that was quite right at https://github.com/astrocatalogs/supernovae/blob/master/SCHEMA.md

Given that, I believe the above point would be better represented as:

```
   {'band': 'H',
    'countrate': '643.7012',
    'e_lower_countrate': '12.7196',
    'e_lower_magnitude': '0.0216675',
    'e_upper_countrate': '12.7196',
    'e_upper_magnitude': '0.0212450',
    'magnitude': '17.97829',
    'source': '3',
    'telescope': 'WIYN',
    'instrument': 'WHIRC',
    'time': '56608.152234',
    'u_time': 'MJD',
    'zeropoint': '25'},
```

**Comment by guillochon** [comment]
Thanks @wmwv! I've made a few fixes:

- Clarified the meaning of `countrate` in the schema (https://github.com/astrocatalogs/supernovae/commit/5d080fc9135ed54145dc9679437f27eb9bb3e51d)
- Fixed the SweetSpot metadata (https://github.com/astrocatalogs/supernovae/commit/390240f1234112d44b15c2abd63f71d6d1344ad6)
- Fixed issue where wrong unit was being tagged to count rates (https://github.com/astrocatalogs/astrocats/commit/806125150d4de34738e77a60c886292e00f633a8)

Changes should appear in ~12 hours.

**Comment by guillochon** [comment]
These issues have now been fixed on the live webpage, closing.

**Comment by wmwv** [comment]
Thanks very much!
