### ISSUE TITLE
[iPTF14bdn] Obviously bogus spectrum phases

### ISSUE THREAD

**Issue by rscalzo** [astrocatalogs/supernovae#81]
The archive reports that all of iPTF14bdn's many spectra were taken almost three years before maximum light (phase range -1090 to -1040).  That's a young supernova indeed!  This is a Ia and not a LBV/impostor, so I assume the spectrum's MJD is just wrong.  The observation dates and date of max on the light curve appear to be correct, cross-checking with Swift data downloaded from SOUSA.

I'm seeing similar issues on spectra associated with many other events.  For example, iPTF13aaz supposedly detected at day -49, iPTF13dkk at day -76, 13dkz at day -110.  These aren't all Ia, but none of them are SN impostors, and I've only found this issue with iPTF SNe so far.

**Comment by guillochon** [comment]
The dates for 14bdn are erroneous on WISeREP, which is where we pulled them from, looks like the original donator there just put in the wrong dates. I'm pointing the WISeREP admin to this issue.

**Comment by guillochon** [comment]
The error has been corrected on WISeREP's end, it will propagate to us in a few days. I'll close once that happens.

**Comment by guillochon** [comment]
Also: Not sure on 13dkk and 13aaz, as you mentioned the photometry/date of max look reasonable.

**Comment by jparrent** [comment]
Thanks @guillochon @rscalzo, I'll monitor as well and see if I can find any other fishy epochs.
