### ISSUE TITLE
[SN2017dfc] z incorrect

### ISSUE THREAD

**Issue by dbishopx** [astrocatalogs/supernovae#82]
Please describe the issue with SN2017dfc's data here, be as descriptive as possible! If you believe the issue appears in other events as well, please identify which other events the issue possibly extends to.

The red shift of 2017dfc is 0.06,   It is actually in a galaxy behind M63.

**Comment by guillochon** [comment]
Thanks @dbishopx! Do you have a source for that information?

**Comment by guillochon** [comment]
Source is here: http://www.astronomerstelegram.org/?read=10302

**Comment by guillochon** [comment]
Change made in https://github.com/astrocatalogs/sne-internal/commit/afffc4586e4513cf0685fe7505d65f7a63f34e7a, will be live tomorrow.

**Comment by guillochon** [comment]
Changes live, closing.
