### ISSUE TITLE
[SN2002cv] Includes both original and S-corrected photometry

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#86]
The data for SN 2002cv includes redundant data for 'R' and 'I'.
It includes both the original reported photometry (Table 3) and the S-corrected photometry (Table 4) for 'R' and 'I'.
http://adsabs.harvard.edu/abs/2008MNRAS.384..107E

Only one of these should be included.  For this particular paper, I would actually suggest that it is the S-corrected photometry that should be include.  Even though, in general I would want the natural system photometry, this paper is an impressive amalgamation of a variety of photometric sources and it seems clearest to just present the S-corrected R, I photometry.  @guillochon  If you have strong feelings one way or the other, please choose based on your preference.

* There's a larger issues of how to clearly report filter systems vs. standard systems and figuring out which each paper is actually reporting.  But that's outside scope for this present ticket.

**Comment by guillochon** [comment]
We actually support storing/displaying both, and toggling between them with a drop-down, but it appears that this is bugged, as this event demonstrates. If you look in the JSON file for this event you can see both photometric datasets (S-corrected and not) are included.

This appears to be an interface issue so hopefully a quick fix.

**Comment by wmwv** [comment]
"We actually support storing/displaying both,"
"If you look in the JSON file for this event you can see both photometric datasets (S-corrected and not) are included."
Oh, that's awesome and perfect.  Congratulations for having already implemented this -- I'm impressed.  I hadn't read the JSON file carefully enough to see this.

How does the interface code decide how to separate repeated events?

E.g., Use Case:"show me all of the observations.  If there are both S-corrected and non-S-corrected, show me the (A) S-corrected version; (B) non S-corrected version.  But if

**Comment by guillochon** [comment]
There's just an attribute on each photometric observation `scorrected:true` if the photometry is S-corrected. Otherwise, that attribute is omitted (most of the time safe to assume not S-corrected, although the absence of the tag simply indicates we don't know).

**Comment by guillochon** [comment]
The "raw" photometry (i.e. no corrections) should display on the page by default now. There's a drop-down menu that in principle would allow the user to toggle between various options (raw, corrected, all), but there appears to be a visibility bug in Bokeh that I am working through.

**Comment by guillochon** [comment]
OK, this is now fixed! Only for 2002cv for now, but will propagate to the rest of the events in the OSC in the next few days.
