### ISSUE TITLE
[PSN J22522345-2036537] Updating name to LSQ12fhs

### ISSUE THREAD

**Issue by kponder** [astrocatalogs/supernovae#87]
Can you update the reference base from PSN J22522345-2036537 to LSQ12fhs?

Thanks!

**Comment by guillochon** [comment]
Hmmm the PSN names are actually already supposed to be de-prioritized relative to all others, but this clearly isn't working. Marking this as a bug, looking into it...

**Comment by guillochon** [comment]
Should be fixed by https://github.com/astrocatalogs/supernovae/commit/bdc4d64e0b0c533688c9975162f6c3d295d6df91, fix will be live after tomorrow's update.

**Comment by guillochon** [comment]
This is fixed, closing.
