### ISSUE TITLE
The OSC Barone-Nugent 12 et al. magnitudes need to be updated to the values in the Erratum:

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#94]
The OSC Barone-Nugent 12 et al. magnitudes need to be updated to the values in the Erratum:

Barone-Nugent 12 et al. had a very important Erratum to update the table of magnitudes, which were largely completely wrong in the originally published paper.  The Erratum can be found at:

https://academic.oup.com/mnrasl/article-lookup/doi/10.1093/mnrasl/slt038

**Comment by guillochon** [comment]
Thanks @wmwv! I've gone ahead and replaced the data with the version in the erratum (https://github.com/astrocatalogs/supernovae/commit/df39f38a9a5b3c634965fbabe59b22a8a0d8bc17); it will go live by tomorrow afternoon.

**Comment by guillochon** [comment]
The data is replaced on the live page, closing.
