### ISSUE TITLE
[SN2005ag] Y:CSP_J, i:CSP_Y, J:CSP_H data duplicated and mixed filters

### ISSUE THREAD

**Issue by wmwv** [astrocatalogs/supernovae#95]
The photometry for SN 2005ag has duplications of very similar data points assigned to different filters.  I suspect a failure of import somewhere.

Specifically the "[instrument_]filter" pairs
Y:CSP_J
i:CSP_Y
J:CSP_H

are duplicate pairs.  I believe the entries with complete "instrument_filter" entries are the correct ones.

**Comment by guillochon** [comment]
I verify that the CSP data bands are occasionally mixed; I had assumed the bands were presented in the same order for all datafiles but that is not correct for some of them (including 05ag).

**Comment by guillochon** [comment]
This should be fixed in https://github.com/astrocatalogs/supernovae/commit/7aecda3899d09cd960f6aee3919763a93928af03, changes will be reflect by tomorrow afternoon.

**Comment by guillochon** [comment]
FYI it looks like 4 supernovae in the CSP dataset were affected.

**Comment by wmwv** [comment]
Thanks for fixing so quickly.  Which 4?

**Comment by guillochon** [comment]
Hmm 5 actually: SN2004gc, SN2005ag, SN2006br, SN2006bd, SN2007jh

**Comment by guillochon** [comment]
The changes should be live now @wmwv, feel free to spot check that the data is now accurate. Closing for now.
