### ISSUE TITLE
[SN1994J] Aliased to distinct supernova AT2017cwa

### ISSUE THREAD

**Issue by dbishopx** [astrocatalogs/supernovae#96]
I was looking up AT2017cwa, and guess what I hit....
https://sne.space/sne/AT2017cwa/

**Comment by guillochon** [comment]
Thanks @dbishopx! Looks like one of the sources there got it wrong. I'll fix.

**Comment by guillochon** [comment]
So this is 3π aliasing to 1994J: http://psweb.mp.qub.ac.uk/ps1threepi/psdb/candidate/1100137031543456500/

I'll pass it on to them.

**Comment by guillochon** [comment]
This is half fixed but for some reason the 3π photometry is still attached to 1994J...looking into it
