### ISSUE TITLE
[SN2015bn] <Missing spectra>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#98]
The spectra are complete up to the end of 2015 (those from Ref 1), but the spectra from 2016 (Ref 2) are missing. I just checked and these spectra are definitely on wiserep.

(Probably unimportant side note: ref 1 and 3 are the same paper)

**Comment by guillochon** [comment]
There was a few week period where we weren't scraping wiserep due to a bug, and some spectra were missed. I've manually refreshed 2015bn and all the spectra should appear after tomorrow's daily update.
